import type { AstroIntegration } from "astro";

const contextualMenuScript = [
	'const contextualActionsStyleId = "cease-nonsense-contextual-actions-style";',
	"",
	"function createMarkdownUrl() {",
	'\tconst href = globalThis.location.href.endsWith("/") ? globalThis.location.href : globalThis.location.href + "/";',
	'\treturn new URL("index.md", href).toString();',
	"}",
	"",
	"function ensureStyles() {",
	'\tif (document.querySelector("#" + contextualActionsStyleId) !== null) return;',
	"",
	'\tconst style = document.createElement("style");',
	"\tstyle.id = contextualActionsStyleId;",
	"\tstyle.textContent = [",
	'\t\t".contextual-actions-parent {",',
	'\t\t"\talign-items: flex-start;",',
	'\t\t"\tdisplay: flex;",',
	'\t\t"\tflex-wrap: wrap;",',
	'\t\t"\tgap: 0.75rem;",',
	'\t\t"\tjustify-content: space-between;",',
	'\t\t"}",',
	'\t\t".contextual-actions {",',
	'\t\t"\tdisplay: inline-flex;",',
	'\t\t"\tflex-wrap: wrap;",',
	'\t\t"\tgap: 0.5rem;",',
	'\t\t"\tmargin-left: auto;",',
	'\t\t"}",',
	'\t\t".contextual-action {",',
	'\t\t"\tbackground: var(--sl-color-bg);",',
	'\t\t"\tborder: 1px solid var(--sl-color-gray-5);",',
	'\t\t"\tborder-radius: 0.5rem;",',
	'\t\t"\tcolor: var(--sl-color-text);",',
	'\t\t"\tcursor: pointer;",',
	'\t\t"\tfont: inherit;",',
	'\t\t"\theight: 2rem;",',
	'\t\t"\tpadding: 0 0.75rem;",',
	'\t\t"\ttext-decoration: none;",',
	'\t\t"}",',
	'\t\t".contextual-action:hover {",',
	'\t\t"\tbackground: var(--sl-color-hairline-light);",',
	'\t\t"}",',
	'\t\t"@media (max-width: 72rem) {",',
	'\t\t"\t.contextual-actions {",',
	'\t\t"\t\tmargin-left: 0;",',
	'\t\t"\t}",',
	'\t\t"}",',
	'\t].join("\\n");',
	"",
	"\tdocument.head.append(style);",
	"}",
	"",
	"async function copyMarkdown(button) {",
	'\tconst originalLabel = button.textContent ?? "Copy page";',
	"",
	"\ttry {",
	"\t\tconst response = await fetch(createMarkdownUrl());",
	"\t\tconst markdown = await response.text();",
	"\t\tawait navigator.clipboard.writeText(markdown);",
	'\t\tbutton.textContent = "Copied";',
	"\t\tglobalThis.setTimeout(() => { button.textContent = originalLabel; }, 2000);",
	"\t} catch (error) {",
	'\t\tconsole.error("Failed to copy markdown", error);',
	"\t}",
	"}",
	"",
	"function initContextualActions() {",
	'\tconst titleElement = document.querySelector(".sl-container > h1");',
	"\tif (!(titleElement instanceof HTMLElement)) return;",
	"",
	"\tconst { parentElement } = titleElement;",
	'\tif (parentElement === null || parentElement.querySelector(".contextual-actions") !== null) return;',
	"",
	"\tensureStyles();",
	"",
	'\tconst actionGroup = document.createElement("div");',
	'\tactionGroup.className = "contextual-actions";',
	"",
	'\tconst copyButton = document.createElement("button");',
	'\tcopyButton.className = "contextual-action";',
	'\tcopyButton.textContent = "Copy page";',
	'\tcopyButton.type = "button";',
	'\tcopyButton.addEventListener("click", () => { void copyMarkdown(copyButton); });',
	"",
	'\tconst viewLink = document.createElement("a");',
	'\tviewLink.className = "contextual-action";',
	"\tviewLink.href = createMarkdownUrl();",
	'\tviewLink.rel = "noreferrer";',
	'\tviewLink.target = "_blank";',
	'\tviewLink.textContent = "View as Markdown";',
	"",
	"\tactionGroup.append(copyButton, viewLink);",
	'\tparentElement.classList.add("contextual-actions-parent");',
	"\tparentElement.append(actionGroup);",
	"}",
	"",
	'if (document.readyState === "loading") {',
	'\tdocument.addEventListener("DOMContentLoaded", initContextualActions, { once: true });',
	"} else {",
	"\tinitContextualActions();",
	"}",
].join("\n");

export default function contextualMenuIntegration(): AstroIntegration {
	return {
		hooks: {
			"astro:config:setup": ({ injectScript }) => {
				injectScript("page", contextualMenuScript);
			},
		},
		name: "cease-nonsense:contextual-menu",
	};
}
